packages:
  - "cms-client"
  - "cms-server"
  - "portfolio"
  - "packages/*"
minimumReleaseAge: 7200
saveExact: true
# note: was commented out when running shadcn init
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
